export const PDF_URL='https://images.engagecdn.net/motorsport-uk-website/production/knowledge-hub/National-competition-rules/2026/Edition-4/Motorsport_UK_NCR_2026_Edition_4.pdf';
export const CHANGES_URL='https://motorsportuk.org/the-sport/regulations/approved-changes/';
const stop=new Set('a an the and or to of for in is it does do must need what how which can should are be i my on with requirements rules'.split(' '));
const aliases={tow:['towing','eye'],hook:['towing'],extinguisher:['extinguishers'],mount:['mountings','mounting'],battery:['batteries'],harness:['harnesses'],helmet:['helmets'],rollcage:['rops','roll','cage'],cutoff:['circuit','breaker'],scrutineer:['scrutineers','scrutiny','scrutineering']};
export function tokens(s){return (s.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(t=>t.length>1&&!stop.has(t));}
export function indexPages(pages,doc){let ch='',app='',part='',title='';const chunks=[];for(const page of pages){const text=page.text;const cm=text.match(/CHAPTER\s+(\d+)\s+([^\n]+)/i);if(cm){if(ch!==cm[1]){app='';part='';}ch=cm[1];title=cm[2].trim();}const footer=text.match(/Chapter\s+(\d+)\s+(?:Part\s+([AB])\s+)?Appendix\s+(\d+)\s*-\s*([^\n]+)/i);if(footer){ch=footer[1];part=footer[2]||'';app=footer[3];title=footer[4].trim();}const am=text.match(/^\s*Appendix\s+(\d+)\s*-\s*([^\n]+)/im);if(am){app=am[1];title=am[2].trim();}const pm=text.match(/^\s*Part\s+([AB])\s*[-–]/im);if(pm)part=pm[1];
const lines=text.split('\n');let buf=[],article='';const flush=()=>{const raw=buf.join('\n').trim();if(raw.length>50)chunks.push({id:`${doc.id}:p${page.page}:${chunks.length}`,docId:doc.id,page:page.page,chapter:ch,appendix:app,part,article,title,text:raw,kind:doc.kind,future:ch==='22'||doc.kind==='future',reference:doc.kind==='base'?`Ch.${ch||'?'}${part?' Part '+part:''}${app?' App.'+app:''}${article?' Art.'+article:''}`:`${doc.name} · PDF page ${page.page}`,effectiveFrom:doc.effectiveFrom||null});};for(const line of lines){if(/Motorsport UK National Competition Rules 2026|^\s*Edition 4\s*$/.test(line))continue;const m=line.match(/^\s*(\d+(?:\.\d+){1,4})\.\s+/);if(m){flush();buf=[];article=m[1];}buf.push(line);if(buf.join('\n').length>2400){flush();buf=[];}}flush();}return chunks;}
export function search(chunks,question,{chapter='',date='',includeFuture=false}={}){const base=tokens(question);if(!base.length)return [];const expanded=[...new Set(base.flatMap(t=>[t,...(aliases[t]||[])]))];const pool=chunks.filter(c=>(!chapter||c.chapter===chapter)&& (includeFuture||!c.future)&&(!date||!c.effectiveFrom||c.effectiveFrom<=date));const df=new Map();const rows=pool.map(c=>{const ts=tokens(c.text+' '+c.title);const f=new Map();for(const t of ts)f.set(t,(f.get(t)||0)+1);for(const t of f.keys())df.set(t,(df.get(t)||0)+1);return {c,f,len:ts.length};});const avg=rows.reduce((a,r)=>a+r.len,0)/(rows.length||1);return rows.map(({c,f,len})=>{let score=0,hits=0;for(const t of expanded){const n=f.get(t)||0;if(!n)continue;hits++;const idf=Math.log(1+(rows.length-(df.get(t)||0)+.5)/((df.get(t)||0)+.5));score+=idf*n*2.2/(n+1.2*(.25+.75*len/(avg||1)));}if(question.length>8&&c.text.toLowerCase().includes(question.toLowerCase()))score+=8;return {...c,score,hits};}).filter(r=>r.score>0&&r.hits>=Math.min(2,base.length)).sort((a,b)=>b.score-a.score).slice(0,12);}
export function validateAnswer(answer,sources){if(!answer||!['supported','context_needed','not_established'].includes(answer.status)||typeof answer.answer!=='string'||!Array.isArray(answer.citations))throw Error('Invalid answer format');const ids=new Set(sources.map(s=>s.id));if(answer.citations.some(id=>!ids.has(id)))throw Error('Answer cited an unavailable source');if(answer.status==='supported'&&!answer.citations.length)throw Error('Answer has no citations');return answer;}
